/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MAIN_PROTOCOL_PB_H_INCLUDED
#define PB_MAIN_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KeyPress {
    uint32_t keyId;
    bool isPressed;
    uint32_t msgOrder;
    uint32_t version;
} KeyPress;

typedef struct _LedBrightness {
    uint32_t ledId;
    uint32_t brightness;
    uint32_t color;
    uint32_t msgOrder;
    uint32_t version;
} LedBrightness;

typedef struct _Packet {
    pb_size_t which_msgType;
    union {
        KeyPress keyPress;
        LedBrightness ledBrightness;
    } msgType;
} Packet;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Packet_init_default                      {0, {KeyPress_init_default}}
#define KeyPress_init_default                    {0, 0, 0, 0}
#define LedBrightness_init_default               {0, 0, 0, 0, 0}
#define Packet_init_zero                         {0, {KeyPress_init_zero}}
#define KeyPress_init_zero                       {0, 0, 0, 0}
#define LedBrightness_init_zero                  {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define KeyPress_keyId_tag                       1
#define KeyPress_isPressed_tag                   2
#define KeyPress_msgOrder_tag                    3
#define KeyPress_version_tag                     4
#define LedBrightness_ledId_tag                  1
#define LedBrightness_brightness_tag             2
#define LedBrightness_color_tag                  3
#define LedBrightness_msgOrder_tag               4
#define LedBrightness_version_tag                5
#define Packet_keyPress_tag                      1
#define Packet_ledBrightness_tag                 2

/* Struct field encoding specification for nanopb */
#define Packet_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msgType,keyPress,msgType.keyPress),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msgType,ledBrightness,msgType.ledBrightness),   2)
#define Packet_CALLBACK NULL
#define Packet_DEFAULT NULL
#define Packet_msgType_keyPress_MSGTYPE KeyPress
#define Packet_msgType_ledBrightness_MSGTYPE LedBrightness

#define KeyPress_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   keyId,             1) \
X(a, STATIC,   SINGULAR, BOOL,     isPressed,         2) \
X(a, STATIC,   SINGULAR, UINT32,   msgOrder,          3) \
X(a, STATIC,   SINGULAR, UINT32,   version,           4)
#define KeyPress_CALLBACK NULL
#define KeyPress_DEFAULT NULL

#define LedBrightness_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ledId,             1) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        2) \
X(a, STATIC,   SINGULAR, UINT32,   color,             3) \
X(a, STATIC,   SINGULAR, UINT32,   msgOrder,          4) \
X(a, STATIC,   SINGULAR, UINT32,   version,           5)
#define LedBrightness_CALLBACK NULL
#define LedBrightness_DEFAULT NULL

extern const pb_msgdesc_t Packet_msg;
extern const pb_msgdesc_t KeyPress_msg;
extern const pb_msgdesc_t LedBrightness_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Packet_fields &Packet_msg
#define KeyPress_fields &KeyPress_msg
#define LedBrightness_fields &LedBrightness_msg

/* Maximum encoded size of messages (where known) */
#define KeyPress_size                            20
#define LedBrightness_size                       30
#define MAIN_PROTOCOL_PB_H_MAX_SIZE              Packet_size
#define Packet_size                              32

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
